from datetime import datetime
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import (
    TA_CENTER,
    TA_LEFT,
)
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import (
    ParagraphStyle,
    getSampleStyleSheet,
)
from reportlab.lib.units import inch
from reportlab.platypus import (
    Image,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)


# =========================================================
# Helpers
# =========================================================

def format_number(value) -> str:
    if value is None:
        return "N/A"

    try:
        return f"{float(value):,.2f}"
    except (TypeError, ValueError):
        return str(value)


def format_percentage(value) -> str:
    if value is None:
        return "N/A"

    try:
        return f"{float(value):+.2f}%"
    except (TypeError, ValueError):
        return str(value)


def format_entity(entity: dict) -> str:
    return ", ".join(
        f"{key}: {value}"
        for key, value in entity.items()
    )


# =========================================================
# Header / Footer
# =========================================================

def add_page_header_footer(
    canvas,
    doc,
):
    canvas.saveState()

    page_width, page_height = A4

    canvas.setFont(
        "Helvetica",
        8,
    )

    canvas.setFillColor(
        colors.grey
    )

    canvas.drawString(
        40,
        page_height - 25,
        "Weekly Business Comparison Report",
    )

    canvas.drawRightString(
        page_width - 40,
        25,
        f"Page {doc.page}",
    )

    canvas.drawString(
        40,
        25,
        "Generated by Weekly Report Analysis Agent",
    )

    canvas.restoreState()


# =========================================================
# AI Markdown-ish renderer
# =========================================================

def add_ai_insights(
    story: list,
    ai_insights: str,
    heading_style,
    body_style,
):
    """
    Convert simple Gemini Markdown into ReportLab
    paragraphs without requiring a Markdown library.
    """

    for raw_line in ai_insights.splitlines():

        line = raw_line.strip()

        if not line:
            story.append(
                Spacer(1, 5)
            )
            continue

        if line.startswith("## "):

            story.append(
                Paragraph(
                    line[3:].strip(),
                    heading_style,
                )
            )

            continue

        if line.startswith("# "):

            story.append(
                Paragraph(
                    line[2:].strip(),
                    heading_style,
                )
            )

            continue

        if line.startswith("- "):

            text = (
                line[2:]
                .replace("**", "")
            )

            story.append(
                Paragraph(
                    f"• {text}",
                    body_style,
                )
            )

            continue

        cleaned = line.replace(
            "**",
            "",
        )

        story.append(
            Paragraph(
                cleaned,
                body_style,
            )
        )


# =========================================================
# PDF generator
# =========================================================

def generate_weekly_report_pdf(
    analysis: dict,
    ai_insights: str | None,
    chart_path: str | Path,
    output_path: str | Path,
    previous_file_name: str,
    current_file_name: str,
    movement_bridge_chart_path: str | Path | None = None,
) -> Path:

    output_path = Path(
        output_path
    )

    chart_path = Path(
        chart_path
    )

    if movement_bridge_chart_path:
        movement_bridge_chart_path = Path(
            movement_bridge_chart_path
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    # =====================================================
    # Styles
    # =====================================================

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Title"],
        fontSize=23,
        leading=28,
        alignment=TA_CENTER,
        spaceAfter=14,
    )

    subtitle_style = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        alignment=TA_CENTER,
        textColor=colors.grey,
        spaceAfter=15,
    )

    section_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=15,
        leading=19,
        spaceBefore=12,
        spaceAfter=9,
    )

    subsection_style = ParagraphStyle(
        "Subsection",
        parent=styles["Heading3"],
        fontSize=11,
        leading=15,
        spaceBefore=8,
        spaceAfter=6,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontSize=9,
        leading=13,
        alignment=TA_LEFT,
        spaceAfter=6,
    )

    small_style = ParagraphStyle(
        "Small",
        parent=body_style,
        fontSize=7.5,
        leading=10,
    )

    # =====================================================
    # Document
    # =====================================================

    document = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=40,
        rightMargin=40,
        topMargin=45,
        bottomMargin=45,
        title="Weekly Business Comparison Report",
    )

    story = []

    # =====================================================
    # 1. Cover / Executive Overview
    # =====================================================

    story.append(
        Spacer(1, 35)
    )

    story.append(
        Paragraph(
            "Weekly Business Comparison Report",
            title_style,
        )
    )

    story.append(
        Paragraph(
            (
                f"<b>Previous:</b> {previous_file_name}"
                "<br/>"
                f"<b>Current:</b> {current_file_name}"
                "<br/>"
                f"<b>Generated:</b> "
                f"{datetime.now().strftime('%d %B %Y %H:%M')}"
            ),
            subtitle_style,
        )
    )

    story.append(
        Spacer(1, 20)
    )

    story.append(
        Paragraph(
            "Executive Overview",
            section_style,
        )
    )

    row_summary = analysis.get(
        "row_summary",
        {},
    )

    overview_data = [
        [
            "Previous Rows",
            "Current Rows",
            "Matched",
            "New",
            "Removed",
        ],
        [
            row_summary.get(
                "previous_rows",
                0,
            ),
            row_summary.get(
                "current_rows",
                0,
            ),
            row_summary.get(
                "matched_rows",
                0,
            ),
            row_summary.get(
                "new_rows",
                0,
            ),
            row_summary.get(
                "removed_rows",
                0,
            ),
        ],
    ]

    overview_table = Table(
        overview_data,
        colWidths=[
            1.25 * inch,
        ] * 5,
    )

    overview_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor(
                        "#E9ECEF"
                    ),
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "ALIGN",
                    (0, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor(
                        "#B7B7B7"
                    ),
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    7,
                ),
            ]
        )
    )

    story.append(
        overview_table
    )

    story.append(
        Spacer(1, 18)
    )

    # =====================================================
    # 2. KPI Performance
    # =====================================================

    story.append(
        Paragraph(
            "KPI Performance",
            section_style,
        )
    )

    metric_summary = analysis.get(
        "metric_summary",
        {},
    )

    metric_data = [
        [
            "Metric",
            "Previous",
            "Current",
            "Change",
            "Change %",
            "Direction",
        ]
    ]

    for metric, values in metric_summary.items():

        metric_data.append(
            [
                Paragraph(
                    str(metric),
                    small_style,
                ),
                format_number(
                    values.get(
                        "previous_total"
                    )
                ),
                format_number(
                    values.get(
                        "current_total"
                    )
                ),
                format_number(
                    values.get(
                        "absolute_change"
                    )
                ),
                format_percentage(
                    values.get(
                        "percentage_change"
                    )
                ),
                str(
                    values.get(
                        "direction",
                        "",
                    )
                ).title(),
            ]
        )

    metric_table = Table(
        metric_data,
        repeatRows=1,
        colWidths=[
            1.15 * inch,
            1.0 * inch,
            1.0 * inch,
            1.0 * inch,
            0.85 * inch,
            0.8 * inch,
        ],
    )

    metric_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor(
                        "#E9ECEF"
                    ),
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor(
                        "#B7B7B7"
                    ),
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (-2, -1),
                    "RIGHT",
                ),
                (
                    "ALIGN",
                    (-1, 1),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    8,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    6,
                ),
            ]
        )
    )

    story.append(
        metric_table
    )

    story.append(
        Spacer(1, 18)
    )

    if chart_path.exists():
        story.append(PageBreak())
        story.append(
            Paragraph(
                "KPI Change Chart",
                section_style,
            )
        )

        story.append(
            Image(
                str(chart_path),
                width=6.6 * inch,
                height=5.3 * inch,
            )
        )

    # =====================================================
    # 3. Movement Bridge
    # =====================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Movement Bridge",
            section_style,
        )
    )

    story.append(
        Paragraph(
            (
                "The movement bridge reconciles the "
                "overall KPI change between continuing, "
                "new and removed entities."
            ),
            body_style,
        )
    )

    movement_bridge = analysis.get(
        "movement_bridge",
        {},
    )

    bridge_data = [
        [
            "Metric",
            "Matched",
            "New",
            "Removed",
            "Explained",
            "Actual",
        ]
    ]

    for metric, values in movement_bridge.items():

        bridge_data.append(
            [
                Paragraph(
                    str(metric),
                    small_style,
                ),
                format_number(
                    values.get(
                        "matched_entity_change"
                    )
                ),
                format_number(
                    values.get(
                        "new_entity_impact"
                    )
                ),
                format_number(
                    values.get(
                        "removed_entity_impact"
                    )
                ),
                format_number(
                    values.get(
                        "explained_change"
                    )
                ),
                format_number(
                    values.get(
                        "actual_total_change"
                    )
                ),
            ]
        )

    bridge_table = Table(
        bridge_data,
        repeatRows=1,
        colWidths=[180, 67, 62, 70, 68, 68],
    )

    bridge_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor(
                        "#E9ECEF"
                    ),
                ),
                (
                    "FONTNAME",
                    (0, 0),
                    (-1, 0),
                    "Helvetica-Bold",
                ),
                (
                    "GRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor(
                        "#B7B7B7"
                    ),
                ),
                (
                    "ALIGN",
                    (1, 1),
                    (-1, -1),
                    "RIGHT",
                ),
                (
                    "FONTSIZE",
                    (0, 0),
                    (-1, -1),
                    7.5,
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    5,
                ),
            ]
        )
    )

    story.append(
        bridge_table
    )

    story.append(
        Spacer(1, 18)
    )

    if (
        movement_bridge_chart_path
        and movement_bridge_chart_path.exists()
    ):

        story.append(
            Image(
                str(
                    movement_bridge_chart_path
                ),
                width=6.3 * inch,
                height=3.5 * inch,
            )
        )

    # =====================================================
    # 4. Major Movements
    # =====================================================

    story.append(
        Paragraph(
            "Major Movements",
            section_style,
        )
    )

    major_movements = analysis.get(
        "major_movements",
        [],
    )

    if major_movements:

        movement_data = [
            [
                "Entity",
                "Metric",
                "Previous",
                "Current",
                "Change",
                "Change %",
            ]
        ]

        for movement in major_movements[:20]:

            movement_data.append(
                [
                    Paragraph(
                        format_entity(
                            movement.get(
                                "entity",
                                {},
                            )
                        ),
                        small_style,
                    ),
                    movement.get(
                        "metric",
                        "",
                    ),
                    format_number(
                        movement.get(
                            "previous_value"
                        )
                    ),
                    format_number(
                        movement.get(
                            "current_value"
                        )
                    ),
                    format_number(
                        movement.get(
                            "absolute_change"
                        )
                    ),
                    format_percentage(
                        movement.get(
                            "percentage_change"
                        )
                    ),
                ]
            )

        movement_table = Table(
            movement_data,
            repeatRows=1,
            colWidths=[
                1.6 * inch,
                0.8 * inch,
                0.85 * inch,
                0.85 * inch,
                0.85 * inch,
                0.75 * inch,
            ],
        )

        movement_table.setStyle(
            TableStyle(
                [
                    (
                        "BACKGROUND",
                        (0, 0),
                        (-1, 0),
                        colors.HexColor(
                            "#E9ECEF"
                        ),
                    ),
                    (
                        "FONTNAME",
                        (0, 0),
                        (-1, 0),
                        "Helvetica-Bold",
                    ),
                    (
                        "GRID",
                        (0, 0),
                        (-1, -1),
                        0.35,
                        colors.HexColor(
                            "#B7B7B7"
                        ),
                    ),
                    (
                        "FONTSIZE",
                        (0, 0),
                        (-1, -1),
                        7,
                    ),
                    (
                        "VALIGN",
                        (0, 0),
                        (-1, -1),
                        "TOP",
                    ),
                    (
                        "ALIGN",
                        (2, 1),
                        (-1, -1),
                        "RIGHT",
                    ),
                    (
                        "TOPPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                    (
                        "BOTTOMPADDING",
                        (0, 0),
                        (-1, -1),
                        4,
                    ),
                ]
            )
        )

        story.append(
            movement_table
        )

    else:

        story.append(
            Paragraph(
                (
                    "No major movements were detected "
                    "using the configured thresholds."
                ),
                body_style,
            )
        )

    # =====================================================
    # 5. New / Removed Entities
    # =====================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Entity Changes",
            section_style,
        )
    )

    story.append(
        Paragraph(
            "New Entities",
            subsection_style,
        )
    )

    new_entities = analysis.get(
        "new_entities",
        [],
    )

    if new_entities:

        for item in new_entities[:20]:

            entity = format_entity(
                item.get(
                    "entity",
                    {},
                )
            )

            values = ", ".join(
                f"{metric}: {format_number(value)}"
                for metric, value
                in item.get(
                    "values",
                    {},
                ).items()
            )

            story.append(
                Paragraph(
                    (
                        f"<b>{entity}</b>"
                        f"<br/>{values}"
                    ),
                    body_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No new entities were detected.",
                body_style,
            )
        )

    story.append(
        Paragraph(
            "Removed Entities",
            subsection_style,
        )
    )

    removed_entities = analysis.get(
        "removed_entities",
        [],
    )

    if removed_entities:

        for item in removed_entities[:20]:

            entity = format_entity(
                item.get(
                    "entity",
                    {},
                )
            )

            values = ", ".join(
                f"{metric}: {format_number(value)}"
                for metric, value
                in item.get(
                    "previous_values",
                    {},
                ).items()
            )

            story.append(
                Paragraph(
                    (
                        f"<b>{entity}</b>"
                        f"<br/>{values}"
                    ),
                    body_style,
                )
            )

    else:

        story.append(
            Paragraph(
                "No removed entities were detected.",
                body_style,
            )
        )

    # =====================================================
    # 6. AI Business Insights
    # =====================================================

    story.append(
        PageBreak()
    )

    story.append(
        Paragraph(
            "Business Insights",
            section_style,
        )
    )

    if ai_insights:

        add_ai_insights(
            story=story,
            ai_insights=ai_insights,
            heading_style=subsection_style,
            body_style=body_style,
        )

    else:

        story.append(
            Paragraph(
                (
                    "AI-generated business insights "
                    "were not requested or were "
                    "temporarily unavailable."
                ),
                body_style,
            )
        )

    # =====================================================
    # Build PDF
    # =====================================================

    document.build(
        story,
        onFirstPage=add_page_header_footer,
        onLaterPages=add_page_header_footer,
    )

    return output_path